FROM caddy:2.6.1-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/caddyserver/replace-response

FROM caddy:2.6.1-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

ADD Caddyfile /etc/caddy/Caddyfile
ADD public/ /usr/share/caddy/

EXPOSE 80
